version: '3.8'

services:
  db:
    image: postgres:16-alpine 
    container_name: ledger_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=sekretnehaslo123
      - POSTGRES_DB=ledger_db
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data 
volumes:
  postgres_data: